CREATE TABLE `ToDo` (
	`ID` BIGINT ( 20 ) NOT NULL AUTO_INCREMENT,
	`Title` VARCHAR ( 200 ) DEFAULT NULL,
	`Description` VARCHAR ( 1024 ) DEFAULT NULL,
	`Reminder` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY ( `ID` ),
UNIQUE KEY `ID_UNIQUE` ( `ID` ) 
);
